------------------ usando uma sequence
create sequence seq_purchase_id
increment by 100
minvalue 1
maxvalue 9999999
start 100;

create table purchase_seq (
	id integer primary key not null default nextval('seq_purchase_id'),
	user_name text not null,
    currency text not null,
    amount int not null
);
------------------ serial
create table purchase_serial (
	id serial PRIMARY KEY,
	user_name text not null,
    currency text not null,
    amount int not null
);

----------------- identify columns

create table purchase_identify (
	id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	user_name text not null,
    currency text not null,
    amount int not null
);
