
insert into legado_cliente (id_cliente, nome, email, genero, state, city, address) values (1, 'Aland Kimmel', 'akimmel0@adobe.com', 'M', 'New York', 'Brooklyn', '349 Garrison Point');
insert into legado_cliente (id_cliente, nome, email, genero, state, city, address) values (2, 'Peg Ixer', 'pixer1@topsy.com', 'F', 'Indiana', 'Indianapolis', '029 Thompson Street');
insert into legado_cliente (id_cliente, nome, email, genero, state, city, address) values (3, 'Marcelline Ramsier', 'mramsier2@indiatimes.com', 'M', 'California', 'Oakland', '21 Talmadge Crossing');
insert into legado_cliente (id_cliente, nome, email, genero, state, city, address) values (4, 'Field Duffit', 'fduffit3@salon.com', 'F', 'Missouri', 'Kansas City', '0 Lerdahl Road');
insert into legado_cliente (id_cliente, nome, email, genero, state, city, address) values (5, 'Binky Le Merchant', 'ble4@house.gov', 'M', 'California', 'Long Beach', '73 Lawn Lane');
insert into legado_cliente (id_cliente, nome, email, genero, state, city, address) values (6, 'Brendon Summerhayes', 'bsummerhayes5@addtoany.com', 'F', 'Florida', 'Lakeland', '2 2nd Junction');
insert into legado_cliente (id_cliente, nome, email, genero, state, city, address) values (7, 'Calvin Womersley', 'cwomersley6@dell.com', 'F', 'Texas', 'Dallas', '90 Luster Junction');
insert into legado_cliente (id_cliente, nome, email, genero, state, city, address) values (8, 'Paolo Childs', 'pchilds7@1688.com', 'F', 'Iowa', 'Des Moines', '4 Crowley Crossing');
insert into legado_cliente (id_cliente, nome, email, genero, state, city, address) values (9, 'Cris McGall', 'cmcgall8@weebly.com', 'M', 'Texas', 'Houston', '59 Kenwood Center');
insert into legado_cliente (id_cliente, nome, email, genero, state, city, address) values (10, 'Tanny Dikelin', 'tdikelin9@vinaora.com', 'M', 'Illinois', 'Chicago', '8 Butternut Parkway');
insert into legado_cliente (id_cliente, nome, email, genero, state, city, address) values (11, 'Issy Pedro', 'ipedroa@seattletimes.com', 'F', 'Ohio', 'Akron', '50 Browning Drive');
insert into legado_cliente (id_cliente, nome, email, genero, state, city, address) values (12, 'Francklyn Kacheler', 'fkachelerb@nifty.com', 'F', 'New York', 'New York City', '13244 Meadow Ridge Court');
insert into legado_cliente (id_cliente, nome, email, genero, state, city, address) values (13, 'Elijah McGeachie', 'emcgeachiec@google.nl', 'M', 'Texas', 'Houston', '3924 Mifflin Point');
insert into legado_cliente (id_cliente, nome, email, genero, state, city, address) values (14, 'Tedd Dayborne', 'tdayborned@blog.com', 'F', 'Missouri', 'Saint Louis', '98 Mifflin Plaza');
insert into legado_cliente (id_cliente, nome, email, genero, state, city, address) values (15, 'Anjela Scrivener', 'ascrivenere@sciencedaily.com', 'M', 'California', 'Oceanside', '23922 Erie Parkway');
insert into legado_cliente (id_cliente, nome, email, genero, state, city, address) values (16, 'Stillman Dunsmore', 'sdunsmoref@symantec.com', 'F', 'Tennessee', 'Kingsport', '56 Sullivan Alley');
insert into legado_cliente (id_cliente, nome, email, genero, state, city, address) values (17, 'Cherlyn Goodright', 'cgoodrightg@bing.com', 'M', 'Michigan', 'Detroit', '4260 Melby Hill');
insert into legado_cliente (id_cliente, nome, email, genero, state, city, address) values (18, 'Brigitte Manjin', 'bmanjinh@live.com', 'M', 'South Carolina', 'Florence', '59 Hollow Ridge Terrace');
insert into legado_cliente (id_cliente, nome, email, genero, state, city, address) values (19, 'Linnet Datte', 'ldattei@yandex.ru', 'F', 'Colorado', 'Englewood', '318 Oneill Park');
insert into legado_cliente (id_cliente, nome, email, genero, state, city, address) values (20, 'Corri Craisford', 'ccraisfordj@marketwatch.com', 'F', 'Florida', 'Fort Lauderdale', '506 Shoshone Drive');
insert into legado_cliente (id_cliente, nome, email, genero, state, city, address) values (21, 'Rafe Stobbs', 'rstobbsk@hud.gov', 'F', 'Oklahoma', 'Tulsa', '3 Garrison Circle');
insert into legado_cliente (id_cliente, nome, email, genero, state, city, address) values (22, 'Zedekiah Snodden', 'zsnoddenl@purevolume.com', 'F', 'California', 'Escondido', '8050 Kedzie Terrace');
insert into legado_cliente (id_cliente, nome, email, genero, state, city, address) values (23, 'Kendell Eborall', 'keborallm@last.fm', 'F', 'Florida', 'Saint Petersburg', '1 Sycamore Drive');
insert into legado_cliente (id_cliente, nome, email, genero, state, city, address) values (24, 'Jarrett Olifaunt', 'jolifauntn@tinypic.com', 'F', 'Pennsylvania', 'Erie', '03 Loomis Avenue');
insert into legado_cliente (id_cliente, nome, email, genero, state, city, address) values (25, 'Kimberlyn Kinsley', 'kkinsleyo@walmart.com', 'F', 'District of Columbia', 'Washington', '5 Anzinger Terrace');
insert into legado_cliente (id_cliente, nome, email, genero, state, city, address) values (26, 'Elaine Lympany', 'elympanyp@tripod.com', 'F', 'New Jersey', 'Newark', '4 Hansons Junction');
insert into legado_cliente (id_cliente, nome, email, genero, state, city, address) values (27, 'Doris Rogez', 'drogezq@microsoft.com', 'M', 'New Mexico', 'Albuquerque', '57769 Meadow Ridge Drive');
insert into legado_cliente (id_cliente, nome, email, genero, state, city, address) values (28, 'Tasia Phare', 'tpharer@google.com.br', 'F', 'Ohio', 'Toledo', '248 La Follette Street');
insert into legado_cliente (id_cliente, nome, email, genero, state, city, address) values (29, 'Woody Dyerson', 'wdyersons@weather.com', 'M', 'Iowa', 'Des Moines', '4655 Gateway Hill');
insert into legado_cliente (id_cliente, nome, email, genero, state, city, address) values (30, 'Ajay Goodlife', 'agoodlifet@phoca.cz', 'M', 'Arkansas', 'North Little Rock', '15431 Pankratz Crossing');
insert into legado_cliente (id_cliente, nome, email, genero, state, city, address) values (31, 'Eleanore Baldinotti', 'ebaldinottiu@chron.com', 'F', 'California', 'San Diego', '95584 Glendale Parkway');
insert into legado_cliente (id_cliente, nome, email, genero, state, city, address) values (32, 'Blisse Kilfedder', 'bkilfedderv@artisteer.com', 'M', 'Missouri', 'Kansas City', '1 Ronald Regan Court');
insert into legado_cliente (id_cliente, nome, email, genero, state, city, address) values (33, 'Trefor Mossop', 'tmossopw@mozilla.org', 'F', 'New York', 'Rochester', '5678 Eagle Crest Alley');
insert into legado_cliente (id_cliente, nome, email, genero, state, city, address) values (34, 'Netty Tollemache', 'ntollemachex@cocolog-nifty.com', 'F', 'Nebraska', 'Omaha', '15 Jana Drive');
insert into legado_cliente (id_cliente, nome, email, genero, state, city, address) values (35, 'Evangeline Gaskin', 'egaskiny@amazonaws.com', 'M', 'New York', 'Rochester', '46289 Carberry Drive');
insert into legado_cliente (id_cliente, nome, email, genero, state, city, address) values (36, 'Viki Wilde', 'vwildez@is.gd', 'F', 'Mississippi', 'Jackson', '594 Bunker Hill Plaza');
insert into legado_cliente (id_cliente, nome, email, genero, state, city, address) values (37, 'Nowell Splevins', 'nsplevins10@google.ca', 'M', 'Florida', 'Orlando', '6 Jenifer Lane');
insert into legado_cliente (id_cliente, nome, email, genero, state, city, address) values (38, 'Berrie Roskam', 'broskam11@blogger.com', 'F', 'Maryland', 'Frederick', '57 Di Loreto Alley');
insert into legado_cliente (id_cliente, nome, email, genero, state, city, address) values (39, 'Irena Fishpoole', 'ifishpoole12@reddit.com', 'F', 'Georgia', 'Lawrenceville', '79 Sutherland Alley');
insert into legado_cliente (id_cliente, nome, email, genero, state, city, address) values (40, 'Merle Coatham', 'mcoatham13@census.gov', 'F', 'Louisiana', 'Shreveport', '86 Elmside Junction');
insert into legado_cliente (id_cliente, nome, email, genero, state, city, address) values (41, 'Hastie Cantu', 'hcantu14@discovery.com', 'F', 'Ohio', 'Akron', '733 Reinke Crossing');
insert into legado_cliente (id_cliente, nome, email, genero, state, city, address) values (42, 'Ian O''Rourke', 'iorourke15@nps.gov', 'M', 'Pennsylvania', 'Pittsburgh', '10134 Cottonwood Park');
insert into legado_cliente (id_cliente, nome, email, genero, state, city, address) values (43, 'Anna-maria Ruppele', 'aruppele16@github.io', 'F', 'Kansas', 'Topeka', '135 4th Parkway');
insert into legado_cliente (id_cliente, nome, email, genero, state, city, address) values (44, 'Ranique Kelcher', 'rkelcher17@nps.gov', 'M', 'Texas', 'Houston', '40 Messerschmidt Junction');
insert into legado_cliente (id_cliente, nome, email, genero, state, city, address) values (45, 'Nara Refford', 'nrefford18@wordpress.org', 'F', 'Tennessee', 'Johnson City', '09 Michigan Plaza');
insert into legado_cliente (id_cliente, nome, email, genero, state, city, address) values (46, 'Kermie Ramsay', 'kramsay19@icq.com', 'F', 'California', 'Los Angeles', '6 Summer Ridge Terrace');
insert into legado_cliente (id_cliente, nome, email, genero, state, city, address) values (47, 'Kit Borrows', 'kborrows1a@twitter.com', 'F', 'Florida', 'Melbourne', '0829 Pierstorff Road');
insert into legado_cliente (id_cliente, nome, email, genero, state, city, address) values (48, 'Nerti Brands', 'nbrands1b@typepad.com', 'M', 'Nevada', 'Las Vegas', '8 Lindbergh Terrace');
insert into legado_cliente (id_cliente, nome, email, genero, state, city, address) values (49, 'Davina Lunbech', 'dlunbech1c@fastcompany.com', 'F', 'Washington', 'Seattle', '5 Luster Lane');
insert into legado_cliente (id_cliente, nome, email, genero, state, city, address) values (50, 'Jermayne Brierley', 'jbrierley1d@dot.gov', 'F', 'West Virginia', 'Charleston', '80136 Burrows Circle');
insert into legado_cliente (id_cliente, nome, email, genero, state, city, address) values (51, 'Jessee MacShirie', 'jmacshirie1e@alexa.com', 'M', 'Texas', 'Houston', '7538 American Ash Center');
insert into legado_cliente (id_cliente, nome, email, genero, state, city, address) values (52, 'Christina Toombs', 'ctoombs1f@fda.gov', 'M', 'Connecticut', 'New Haven', '67 Jenna Avenue');
insert into legado_cliente (id_cliente, nome, email, genero, state, city, address) values (53, 'Vitia Pudden', 'vpudden1g@sbwire.com', 'F', 'Kentucky', 'Lexington', '149 Nobel Hill');
insert into legado_cliente (id_cliente, nome, email, genero, state, city, address) values (54, 'Margaretha Shapiro', 'mshapiro1h@cnet.com', 'F', 'Illinois', 'Chicago', '33 Bartelt Trail');
insert into legado_cliente (id_cliente, nome, email, genero, state, city, address) values (55, 'Brett Pesterfield', 'bpesterfield1i@ibm.com', 'M', 'Oregon', 'Portland', '6348 Merry Avenue');
insert into legado_cliente (id_cliente, nome, email, genero, state, city, address) values (56, 'Viviana Kerswell', 'vkerswell1j@slideshare.net', 'M', 'Indiana', 'Gary', '250 Northfield Junction');
insert into legado_cliente (id_cliente, nome, email, genero, state, city, address) values (57, 'Sandy Girardey', 'sgirardey1k@timesonline.co.uk', 'M', 'Michigan', 'Flint', '35493 Spohn Alley');
insert into legado_cliente (id_cliente, nome, email, genero, state, city, address) values (58, 'Terese Navan', 'tnavan1l@huffingtonpost.com', 'M', 'Virginia', 'Roanoke', '7992 Leroy Lane');
insert into legado_cliente (id_cliente, nome, email, genero, state, city, address) values (59, 'Karoly Beddo', 'kbeddo1m@ezinearticles.com', 'M', 'Pennsylvania', 'Philadelphia', '99 Hansons Parkway');
insert into legado_cliente (id_cliente, nome, email, genero, state, city, address) values (60, 'Emalee Pentony', 'epentony1n@ameblo.jp', 'F', 'Nevada', 'Las Vegas', '6995 Loftsgordon Place');
insert into legado_cliente (id_cliente, nome, email, genero, state, city, address) values (61, 'Roz Belch', 'rbelch1o@yandex.ru', 'F', 'Michigan', 'Warren', '5545 Schiller Center');
insert into legado_cliente (id_cliente, nome, email, genero, state, city, address) values (62, 'Jefferey Zipsell', 'jzipsell1p@craigslist.org', 'M', 'South Carolina', 'Greenville', '8721 Granby Alley');
insert into legado_cliente (id_cliente, nome, email, genero, state, city, address) values (63, 'Ivar Pinkie', 'ipinkie1q@cocolog-nifty.com', 'M', 'Michigan', 'Grand Rapids', '489 Steensland Plaza');
insert into legado_cliente (id_cliente, nome, email, genero, state, city, address) values (64, 'Rubetta Ridett', 'rridett1r@bloglovin.com', 'F', 'Louisiana', 'Monroe', '18 Lyons Crossing');
insert into legado_cliente (id_cliente, nome, email, genero, state, city, address) values (65, 'Arlina Altimas', 'aaltimas1s@europa.eu', 'M', 'Texas', 'Austin', '621 Jackson Trail');
insert into legado_cliente (id_cliente, nome, email, genero, state, city, address) values (66, 'Rustie Dimont', 'rdimont1t@cocolog-nifty.com', 'F', 'Texas', 'Denton', '1 Dwight Court');
insert into legado_cliente (id_cliente, nome, email, genero, state, city, address) values (67, 'Jerrilyn Mayhew', 'jmayhew1u@usda.gov', 'F', 'California', 'San Francisco', '87 Debra Street');
insert into legado_cliente (id_cliente, nome, email, genero, state, city, address) values (68, 'Shirley Allenson', 'sallenson1v@bloglines.com', 'M', 'Georgia', 'Duluth', '86 Melby Center');
insert into legado_cliente (id_cliente, nome, email, genero, state, city, address) values (69, 'Marian Strodder', 'mstrodder1w@economist.com', 'F', 'Texas', 'El Paso', '7413 Upham Terrace');
insert into legado_cliente (id_cliente, nome, email, genero, state, city, address) values (70, 'Callie Waterhouse', 'cwaterhouse1x@nymag.com', 'F', 'Florida', 'Tallahassee', '93777 Mcguire Place');
insert into legado_cliente (id_cliente, nome, email, genero, state, city, address) values (71, 'Merrili Gorger', 'mgorger1y@guardian.co.uk', 'M', 'Texas', 'Austin', '8 Division Parkway');
insert into legado_cliente (id_cliente, nome, email, genero, state, city, address) values (72, 'Desi Bool', 'dbool1z@dion.ne.jp', 'M', 'South Carolina', 'Myrtle Beach', '423 Elgar Avenue');
insert into legado_cliente (id_cliente, nome, email, genero, state, city, address) values (73, 'Meggie Blundell', 'mblundell20@fema.gov', 'M', 'Pennsylvania', 'Pittsburgh', '2 Northview Court');
insert into legado_cliente (id_cliente, nome, email, genero, state, city, address) values (74, 'Ansell Tinn', 'atinn21@vistaprint.com', 'F', 'California', 'Riverside', '7803 Bay Point');
insert into legado_cliente (id_cliente, nome, email, genero, state, city, address) values (75, 'Riobard Rosendahl', 'rrosendahl22@weebly.com', 'M', 'Texas', 'Arlington', '305 Mockingbird Road');
insert into legado_cliente (id_cliente, nome, email, genero, state, city, address) values (76, 'Babette Glyssanne', 'bglyssanne23@wsj.com', 'M', 'Georgia', 'Macon', '94286 Mayfield Junction');
insert into legado_cliente (id_cliente, nome, email, genero, state, city, address) values (77, 'Caron Goodier', 'cgoodier24@spotify.com', 'M', 'Washington', 'Spokane', '7172 Mifflin Trail');
insert into legado_cliente (id_cliente, nome, email, genero, state, city, address) values (78, 'Viv Pietz', 'vpietz25@t.co', 'M', 'Kentucky', 'Louisville', '1 Manitowish Park');
insert into legado_cliente (id_cliente, nome, email, genero, state, city, address) values (79, 'Parker Chrippes', 'pchrippes26@pagesperso-orange.fr', 'M', 'Florida', 'Pensacola', '846 Magdeline Hill');
insert into legado_cliente (id_cliente, nome, email, genero, state, city, address) values (80, 'Balduin Gilffillan', 'bgilffillan27@timesonline.co.uk', 'F', 'Alabama', 'Birmingham', '9 Mayer Court');
insert into legado_cliente (id_cliente, nome, email, genero, state, city, address) values (81, 'Barbee Waddington', 'bwaddington28@google.co.uk', 'F', 'Wisconsin', 'Milwaukee', '0 Mosinee Hill');
insert into legado_cliente (id_cliente, nome, email, genero, state, city, address) values (82, 'Alix Arangy', 'aarangy29@bing.com', 'M', 'Colorado', 'Denver', '1460 Darwin Parkway');
insert into legado_cliente (id_cliente, nome, email, genero, state, city, address) values (83, 'Lon De Blasio', 'lde2a@sogou.com', 'F', 'Louisiana', 'New Orleans', '501 Brentwood Hill');
insert into legado_cliente (id_cliente, nome, email, genero, state, city, address) values (84, 'Hildagard Riddle', 'hriddle2b@constantcontact.com', 'M', 'Arizona', 'Phoenix', '2291 Southridge Trail');
insert into legado_cliente (id_cliente, nome, email, genero, state, city, address) values (85, 'Don Falcus', 'dfalcus2c@g.co', 'M', 'Kansas', 'Shawnee Mission', '458 Meadow Vale Lane');
insert into legado_cliente (id_cliente, nome, email, genero, state, city, address) values (86, 'Dari Busfield', 'dbusfield2d@discuz.net', 'F', 'West Virginia', 'Charleston', '2 Comanche Pass');
insert into legado_cliente (id_cliente, nome, email, genero, state, city, address) values (87, 'Paxon Kidstoun', 'pkidstoun2e@sfgate.com', 'M', 'Texas', 'Mesquite', '8 Glendale Street');
insert into legado_cliente (id_cliente, nome, email, genero, state, city, address) values (88, 'Gardner Pauly', 'gpauly2f@home.pl', 'M', 'Florida', 'Fort Myers', '7 Miller Way');
insert into legado_cliente (id_cliente, nome, email, genero, state, city, address) values (89, 'Terri-jo MacKee', 'tmackee2g@unc.edu', 'F', 'New York', 'Staten Island', '10 Dahle Circle');
insert into legado_cliente (id_cliente, nome, email, genero, state, city, address) values (90, 'Perle Dawidowitsch', 'pdawidowitsch2h@illinois.edu', 'F', 'Florida', 'Tallahassee', '2852 Menomonie Junction');
insert into legado_cliente (id_cliente, nome, email, genero, state, city, address) values (91, 'Ivar Stead', 'istead2i@redcross.org', 'M', 'California', 'Sacramento', '3410 Westridge Way');
insert into legado_cliente (id_cliente, nome, email, genero, state, city, address) values (92, 'Sophey Fosbraey', 'sfosbraey2j@msn.com', 'M', 'Colorado', 'Fort Collins', '87115 Merry Terrace');
insert into legado_cliente (id_cliente, nome, email, genero, state, city, address) values (93, 'Purcell MacChaell', 'pmacchaell2k@weather.com', 'F', 'Florida', 'Fort Lauderdale', '55 Jackson Parkway');
insert into legado_cliente (id_cliente, nome, email, genero, state, city, address) values (94, 'Fee Oxbrough', 'foxbrough2l@slate.com', 'M', 'North Carolina', 'Greensboro', '65201 Sullivan Crossing');
insert into legado_cliente (id_cliente, nome, email, genero, state, city, address) values (95, 'Bartie Ratnege', 'bratnege2m@smugmug.com', 'F', 'Colorado', 'Littleton', '932 Pine View Avenue');
insert into legado_cliente (id_cliente, nome, email, genero, state, city, address) values (96, 'Toiboid Yurenin', 'tyurenin2n@nifty.com', 'F', 'California', 'San Jose', '81 Glacier Hill Crossing');
insert into legado_cliente (id_cliente, nome, email, genero, state, city, address) values (97, 'Myrilla Tarborn', 'mtarborn2o@privacy.gov.au', 'M', 'District of Columbia', 'Washington', '5 Rowland Alley');
insert into legado_cliente (id_cliente, nome, email, genero, state, city, address) values (98, 'Germain Mitton', 'gmitton2p@parallels.com', 'M', 'District of Columbia', 'Washington', '739 Corscot Road');
insert into legado_cliente (id_cliente, nome, email, genero, state, city, address) values (99, 'Aleece Jickells', 'ajickells2q@mediafire.com', 'F', 'Pennsylvania', 'Philadelphia', '926 Rigney Park');
insert into legado_cliente (id_cliente, nome, email, genero, state, city, address) values (100, 'Corrine Carcass', 'ccarcass2r@uiuc.edu', 'M', 'Alabama', 'Montgomery', '00 Crescent Oaks Crossing');
